### ISSUE TITLE
phantomJs stdout/stderr are visible, is that correct?

### ISSUE THREAD

**Issue by giacecco** [alexscheelmeyer/node-phantom#2]
Hi alexscheelmeyer,
Using node-phantom always displays the underlying phantomJs console output when executing, I just wanted to know  if this is what you wanted or a side effect of your code being still in a 'debugging' stage. Below are a few sample lines of what I get on my Ubuntu:

```
phantom stdout: 2012-08-16T08:07:44 [DEBUG] Got bus address:  "unix:abstract=/tmp/dbus-RyR7SBz8te,guid=18c8415be3d1b8357dd72d8300000019" 
2012-08-16T08:07:44 [DEBUG] Connected to accessibility bus at:  "unix:abstract=/tmp/dbus-RyR7SBz8te,guid=18c8415be3d1b8357dd72d8300000019" 
2012-08-16T08:07:44 [DEBUG] Registered DEC:  true 
2012-08-16T08:07:45 [DEBUG] Registered event listener change listener:  true 
phantom stderr: 2012-08-16T08:07:46 [WARNING] QFont::setPixelSize: Pixel size <= 0 (0)
```

Thanks.

G.

**Comment by alexscheelmeyer** [comment]
This seems to be an issue with PhantomJS on Ubuntu, I am not getting these on Mac OS X (although I sometimes get "phantom stderr: Keyboard Layouts: duplicate keyboard layout identifier 5591." instead).
It would be nice to be able to hijack the outputs from PhantomJS though, instead of simply printing them to stdout and stderr. This would allow you to act on or silently ignore unexpected output from PhantomJS. In my experience any output from PhantomJS is unexpected so that is why it works like this currently.
I will take a look at allowing you to hijack the output.

**Comment by giacecco** [comment]
Thanks. It is not a priority from my perspective though as what I am developing using your library is 'headless'. Get back to me if you need me to do some testing on Ubuntu.
