### ISSUE TITLE
Tests not running successfully?

### ISSUE THREAD

**Issue by jmhnilbog** [alexscheelmeyer/node-phantom#52]
Phantomjs 1.9.0 installed, node v0.10.6.

Tests don't succeed in version 694980061531d75299f959e9db9d788a6695c19b.

`npm test` fails because it hasn't been updated to run mocha.

`mocha` results in...

```
$ mocha

  ․․․․․․․․․․․․․․․․phantom stderr: execvp(): No such file or directory

․

  ✖ 2 of 17 tests failed:

  1) Phantom Create should change behavior on different phantomPath:
     Error: spawn ENOENT
      at errnoException (child_process.js:980:11)
      at Process.ChildProcess._handle.onexit (child_process.js:771:34)

  2) Phantom should be able to inject js:
     Error: timeout of 2000ms exceeded
      at null.<anonymous> (/usr/lib/node_modules/mocha/lib/runnable.js:167:14)
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

For what it's worth, I can't get phantomjs-node working correctly today either, but that looks like a dnode problem.

**Comment by alexscheelmeyer** [comment]
What do you mean "can't get phantomjs-node working correctly today either"? It seems these problems with the tests are entirely inconsequential to node-phantom working for real use - are you planning on doing development?

In any case I have fixed the npm test issue and tried to modify the tests to not fail in your case. I can't guarantee anything though since I am not able to reproduce the failed tests you see.

You will need to pull from github since I am not updating npm at this point.
