### ISSUE TITLE
Footer's contents seems don't work

### ISSUE THREAD

**Issue by skotchio** [alexscheelmeyer/node-phantom#57]
I'm trying create custom footers such in phantomjs examples: https://github.com/ariya/phantomjs/blob/master/examples/printheaderfooter.js

Here is my code:

```
var phantom = require('node-phantom');

phantom.create(function (err, ph) {
    ph.createPage(function (err, page) {
         page.set('paperSize', {
              format: 'A4',
              orientation: 'portrait',
              footer: {
                contents: ph.callback(function (pageNum, numPages) {
                  if (pageNum == 1) {
                    return "";
                  }
                  return "<h1>Header <span style='float:right'>" + pageNum + " / " + numPages + "</span></h1>";
                })
              }
         }, function () {
             page.open('http://www.google.com', function () {
              })
         })
    })
});
```

But unfortunately I get the following error:

```
TypeError: Object #<Object> has no method 'callback';
```

Is it bug that ph does not expose callback method?

**Comment by alexscheelmeyer** [comment]
Hmm, I dont think this would work regardless of callback method or not. Currently the "set" method is used for setting values and those values are serialized at the node end and sent across to phantomjs for actual setting. The problem is that the serialization will not work for an object that contains methods.

I think to support this, one would need a very special "papersize" method on the page object that knows to expect methods as some arguments and serialize them properly.

I dont think it is something that is high on the priority list for me right now. So if it is important to you, you could do a pull request.
